[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mixtape"
version = "0.0.0"
requires-python = ">=3.12"
license = { text = "Apache 2.0" }
dependencies = [
  "celery",
  "django[argon2]",
  "django-allauth",
  "django-auth-style",
  "django-cors-headers",
  "django-environ",
  "django-extensions",
  "django-filter",
  "django-oauth-toolkit",
  "django-resonant-settings[allauth]",
  "django-resonant-utils",
  "djangorestframework",
  "drf-yasg",
  "psycopg[binary]",
  "rich",
  "whitenoise[brotli]",
  # Production-only
  "django-s3-file-field[s3]",
  "django-storages[s3]",
  "gunicorn",
  "sentry-sdk[celery,django]",
]

[project.optional-dependencies]
dev = [
  "django-browser-reload",
  "django-debug-toolbar",
  "django-minio-storage",
  "django-s3-file-field[minio]",
  "ipython",
  "tox",
]

[tool.hatch.build]
packages = [
  "mixtape",
]

[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 100
# Sort by name, don't cluster "from" vs "import"
force_sort_within_sections = true
# Combines "as" imports on the same line
combine_as_imports = true

[tool.mypy]
files = [
  "mixtape",
]
show_error_codes = true
ignore_missing_imports = true
plugins = [
    "mypy_django_plugin.main",
]

[tool.django-stubs]
django_settings_module = "mixtape.settings.testing"

[tool.pytest.ini_options]
addopts = [
  # Test utilies should be imported absolutely from the pythonpath,
  # so use the Pytest-reccomended "importlib" mode
  "--import-mode=importlib",
  "--strict-config",
  "--strict-markers",
  "--showlocals",
  "--verbose",
]
filterwarnings = [
  "error",
]
DJANGO_SETTINGS_MODULE = "mixtape.settings.testing"
